---
title: "Untitled"
author: "Nicholas Seah"
date: "5/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glue)
library(english)
```

```{r}
xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")
```

```{r}
pluralize_gift <- function(gift){

gift <- gift %>%
  paste("s", sep = "") %>%
  str_replace_all("ys$", "ies") %>%
  str_replace_all("ooses$", "eese") %>%
    str_replace_all("ges$", "ge")

return(gift)
}
```

```{r}
make_phrase <- function(num, num_word, item, verb, adjective, location){

  verb <- str_replace_na(verb, "")
  adjective <- str_replace_na(adjective, "")
  location <- str_replace_na(location, "")
  item <- if (num > 1){
    pluralize_gift(item) 
  } else {
    item}
  num_word <- as.character(english(num)) %>%
    str_replace_all("one", "and a")
  
  glue("{num_word} {adjective} {item} {verb} {location}") %>%
    str_trim("both") %>%
    str_replace_all("  ", " ")

}

xmas <- xmas %>%
  mutate(
    Full.Phrase = pmap(xmas, ~make_phrase(..1, ..2, ..3, ..4, ..5, ..6))
  )

```

```{r}
sing_day <- function(dataset, line, phrase_col){

  phrases <- dataset %>% pull({{phrase_col}})
  song_phrases <- phrases[line:1]
  
  line <- ordinal(line)
  chorus <- glue("On the {line} day of Christmas, my true love sent to me,") 
  
  gifts <- str_c(song_phrases, collapse = ", \n")
  
  glue("{chorus} \n{gifts}")
  

}
sing_day(xmas, 3, Gift.Item)
```

```{r}
usethis::use_package("twelvedays")
```

```{r}
test_that("pluralize_gift works", {
  expect_match(pluralize_gift("Jello"), "Jellos")
})
```



